backend:
  name: git-gateway
  branch: master
#backend går att ändra till "github" i framtiden, vilket gör att användare kan logga in i cms:et med sitt guithub-konto


media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow


collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/se/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "case"
    label: "Case"
    folder: "src/pages/se/kunder"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Linkedinbild", name: linkedinbild, widget: image}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Sidebar", name: intro, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Ikon, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},{label: Rubrik, name: rubrik, widget: string}, {label: Text, name: text, widget: text}]}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "Verticals"
    create: true
    label: "Vertikalsidor"
    folder: "src/pages/se/losningar/"
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vertical-page"}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string, hint: Metabeskrivning för Google och sociala medier}
      - {label: Hero, name: hero, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Rubrik, name: heading, widget: text}, {label: Punktlista, name: list, widget: list, fields: [{label: Punkt, name: listObject, widget: string}]}]}
      - {label: "USP's", name: intro, widget: object, fields: [{label: Rubrik, name: heading, widget: string}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Ikon, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},{label: Rubrik, name: rubrik, widget: string}, {label: Text, name: text, widget: text}]}]}
      - {label: USP-text, name: usp, widget: object, fields: [{label: Bild, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},{label: Rubrik, name: heading, widget: string}, {label: Text, name: text, widget: text}, {label: Knapptext, name: string, widget: string}]}
      - {label: Heading, name: heading, widget: string}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/se/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: heroImage, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      
      
      - file: "src/pages/se/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

